// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAMGlQxGLjdCaje-KI0aL_JzOVtIO4ctE',
    appId: '1:152634568500:web:7eb58bdc8d5a45c9cebf61',
    messagingSenderId: '152634568500',
    projectId: 'library-44c60',
    authDomain: 'library-44c60.firebaseapp.com',
    storageBucket: 'library-44c60.firebasestorage.app',
    measurementId: 'G-C3VX8V9GDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxPM2IlRlLQVME1hj6AJXDoaE-CSsuyPo',
    appId: '1:152634568500:android:40098ceb846bd400cebf61',
    messagingSenderId: '152634568500',
    projectId: 'library-44c60',
    storageBucket: 'library-44c60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6GaOco8w2_dq9Q4YeEV1w7_EjvQfnzPE',
    appId: '1:152634568500:ios:80397aafb3214a3ecebf61',
    messagingSenderId: '152634568500',
    projectId: 'library-44c60',
    storageBucket: 'library-44c60.firebasestorage.app',
    iosClientId: '152634568500-9r49ghqjlt6klq0mhmbvlcfj236o2fro.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6GaOco8w2_dq9Q4YeEV1w7_EjvQfnzPE',
    appId: '1:152634568500:ios:80397aafb3214a3ecebf61',
    messagingSenderId: '152634568500',
    projectId: 'library-44c60',
    storageBucket: 'library-44c60.firebasestorage.app',
    iosClientId: '152634568500-9r49ghqjlt6klq0mhmbvlcfj236o2fro.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAMGlQxGLjdCaje-KI0aL_JzOVtIO4ctE',
    appId: '1:152634568500:web:14f0e0f701f19097cebf61',
    messagingSenderId: '152634568500',
    projectId: 'library-44c60',
    authDomain: 'library-44c60.firebaseapp.com',
    storageBucket: 'library-44c60.firebasestorage.app',
    measurementId: 'G-BYBMH3ZK1B',
  );
}
